### ISSUE TITLE
Coral talk does not load in my webpage

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [coralproject/ask-docs#117]
Hello,

Hope all is well.
In our company we are trying to add talk commenting to our website.
After installation here is the snippet we got from configuration to add in our webpage:

Use this one instead. It uses docker

<div id="coral_talk_stream"></div>
<script src="http://someurl.compute-1s.com:3000/static/embed.js" async onload="
  Coral.Talk.render(document.getElementById('coral_talk_stream'), {
    talk: 'http://ec2-34-227-57-44.compute-1.amazonaws.com:3000/'
  });
"></script>

So far so good however what we need is more than this. We are using reactjs single page application and we need to have more than one talk stream in our 
page lets say in each page we have 20 news and consequently we need 20 commnets template for each.
To be able to achieve that I copied the code provided here by talk:

http://ec2-34-227-57-44.compute-1.amazonaws.com:3000/static/embed.js 

in our code base repository and then I initialized it as follow

`import {Coral} from '../../../tj-common-widget/Coral';

export class Test extends React.Component {

    constructor(props) {
        super();
    }

    componentDidMount() {
       this.coralTest();

    }

    coralTest=()=>{

        Coral.Talk.render(document.getElementById('coral_talk_stream'), { //Later on we are planning to change it to getElementByClass to fit more than 1 talk            talk: 'http://ec2-34-227-57-44.compute-1.amazonaws.com:3000/'
        });
 
    }

    render() {

   

        return (
                  <div id="coral_talk_stream"></div>
        )
    }
}

export default test;`

When I run the above code nothing will happen. Is it possible to help me why does it not work? 
Also is it possible to have multiple talks in one page(example:20 stories 20 talk in a single page)?

Thanks a lot

**Comment by kgardnr** [comment]
Hi there! Glad to hear you’re using talk! Would you mind reposting this in
the talk repo issues, please, and our team will review and respond.

**Comment by hminaeeBrunswicknews** [comment]
Here you are: 
[https://github.com/coralproject/talk/issues/1684](url)

Thanks
